name: Quality Check

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: pip install uv
      - name: Create venv for uv
        run: uv venv
      - name: Activate venv & run quality checks
        run: |
          source .venv/bin/activate
          bash scripts/quality.sh
      - name: Run tests
        run: |
          source .venv/bin/activate
          uv run pytest --maxfail=1 --disable-warnings -v
